# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PK.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QColor
from PyQt5.QtWidgets import QLCDNumber
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    central_widget = None
    pushButton_result_path_edit = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(304, 430)
        MainWindow.setMinimumSize(QtCore.QSize(304, 410))
        MainWindow.setMaximumSize(QtCore.QSize(304, 410))
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("centralwidget")
        self.central_widget.setStyleSheet("""
        QWidget {
            background-color: rgb(80, 80, 80);
            }
        """)
        self.pushButton_result_path_edit = QtWidgets.QPushButton(self.central_widget)
        self.pushButton_result_path_edit.setGeometry(QtCore.QRect(220, 50, 75, 20))
        self.pushButton_result_path_edit.setObjectName("pushButton_2")
        self.pushButton_result_path_edit.setStyleSheet("""QWidget {
            border: 1px solid rgb(10, 151, 158);
            border-radius: 7px;
            background-color: rgb(100, 100, 100);
            }
            QPushButton:pressed {background-color: rgb(70, 70, 70)}
            """)
        self.mainlabel = QtWidgets.QLabel(self.central_widget)
        self.mainlabel.setGeometry(QtCore.QRect(10, 20, 201, 20))
        self.mainlabel.setObjectName("lineEdit")
        self.lineEdit_result_path = QtWidgets.QLineEdit(self.central_widget)
        self.lineEdit_result_path.setGeometry(QtCore.QRect(10, 50, 200, 20))
        self.lineEdit_result_path.setObjectName("lineEdit_2")
        self.lineEdit_result_path.setStyleSheet("""QWidget {
            border: 1px solid grey;
            border-radius: 7px;
            background-color: rgb(50, 50, 50);
            color: rgb(20, 201, 208)
            }""")
        self.spinBox = QtWidgets.QSpinBox(self.central_widget)
        self.spinBox.setGeometry(QtCore.QRect(210, 290, 51, 22))
        self.spinBox.setObjectName("spinBox")
        self.spinBox.setStyleSheet("""
        QWidget {
            border: 1px solid black;
            border-radius: 10px;
            color: rgb(20, 201, 208);
            background-color: rgb(50, 50, 50);
            border-top-right-radius: 0px;
            border-bottom-right-radius: 0px;
            }
        QSpinBox::up-button {border: 0px solid black;
                            border-bottom: 1px solid black;
                            background-color: rgb(90, 90, 90);
                            }
        QSpinBox::up-button:pressed {border: 1px solid rgb(20, 201, 208);
                                     background-color: rgb(50, 50, 50);}
                            
        QSpinBox::down-button {border: 0px solid black;
                               color: rgb(255,155,155);
                               border-top: 1px solid black;
                               background-color: rgb(90, 90, 90);
                               }
        QSpinBox::down-button:pressed {border: 1px solid rgb(20, 201, 208);
                                     background-color: rgb(50, 50, 50);}
        """)
        self.time_add = QtWidgets.QPushButton(self.central_widget)
        self.time_add.setGeometry(QtCore.QRect(260, 290, 22, 22))
        self.time_add.setStyleSheet("""
        QWidget {
            border: 1px solid black;
            border-radius: 10px;
            border-top-left-radius: 0px;
            border-bottom-left-radius: 0px;
            background-color: rgb(90, 90, 90);
            }
            QPushButton:pressed {background-color: rgb(70, 70, 70)}
            """)
        self.time_add.setObjectName("time_add")
        self.error_message = QtWidgets.QMessageBox
        self.label = QtWidgets.QLabel(self.central_widget)
        self.label.setGeometry(QtCore.QRect(220, 270, 61, 20))
        self.label.setObjectName("label")
        self.label.setStyleSheet("""QWidget{color: rgb(20, 201, 208)}""")
        self.lcdNumber = QtWidgets.QLCDNumber(self.central_widget)
        self.lcdNumber.setGeometry(QtCore.QRect(120, 340, 51, 31))
        self.lcdNumber.setSegmentStyle(QLCDNumber.Flat)
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber.setStyleSheet("""QLCDNumber{color:rgb(0, 0, 0);
                                        background-color:rgb(50, 50, 50);
                                        border: 1px solid grey;
                                        border-radius: 8px;}""")
        self.pushButton_start = QtWidgets.QPushButton(self.central_widget)
        self.pushButton_start.setGeometry(QtCore.QRect(210, 332, 71, 50))
        self.pushButton_start.setStyleSheet("""
        QWidget {
            border: 1px solid black;
            border-radius: 10px;
            background-color: rgb(90, 90, 90);
            }
        QPushButton:pressed {background-color: rgb(70, 70, 70)} 
        """)
        self.pushButton_start.setObjectName("pushButton_3")
        self.pushButton_stop = QtWidgets.QPushButton(self.central_widget)
        self.pushButton_stop.setGeometry(QtCore.QRect(20, 330, 61, 51))
        self.pushButton_stop.setObjectName("pushButton_4")
        self.pushButton_stop.setStyleSheet("""
                QWidget {
            border: 1px solid red;
            border-radius: 10px;
            background-color: rgb(90, 90, 90);
            }
        QPushButton:pressed {background-color: rgb(70, 70, 70)}
        """)
        self.label_2 = QtWidgets.QLabel(self.central_widget)
        self.label_2.setGeometry(QtCore.QRect(98, 100, 108, 16))
        self.label_2.setObjectName("label_2")
        self.label_2.setStyleSheet("""QWidget{
                                    border: 1px solid grey;
                                    color: rgb(20, 201, 208);
                                    background-color: rgb(50, 50, 50);
                                    border-radius: 8px}""")
        self.label_3 = QtWidgets.QLabel(self.central_widget)
        self.label_3.setGeometry(QtCore.QRect(15, 270, 150, 15))

        self.label_3.setStyleSheet("""QWidget{
                                            color: rgb(20, 201, 208);
                                            }""")
        self.textBrowser = QtWidgets.QTextBrowser(self.central_widget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 120, 281, 121))
        self.textBrowser.setStyleSheet("""
        QWidget {
            border: 1px solid grey;
            border-radius: 10px;
            background-color: rgb(50, 50, 50);
            }
        
        """)
        self.textBrowser.setTextColor(QColor(20, 201, 208))
        self.textBrowser.setObjectName("textBrowser")
        self.progressBar = QtWidgets.QProgressBar(self.central_widget)
        self.progressBar.setGeometry(QtCore.QRect(10, 250, 281, 16))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.setStyleSheet("""
QProgressBar{
    border: 1px solid grey;
    background-color: rgb(50, 50, 50);
    border-radius: 5px;
    text-align: center;
    color: rgb(0, 150, 158)
}

QProgressBar::chunk {
    background-color: rgb(20, 201, 210);
    text-color: rgb(20, 201, 210);
    border-radius: 5px;
    
}
""")
        MainWindow.setCentralWidget(self.central_widget)
        # self.statusBar = QtWidgets.QStatusBar(MainWindow)
        # self.statusBar.setObjectName("statusBar")
        # self.statusBar.setWindowIconText('sssss')
        # self.statusBar.setStyleSheet("""QWidget {
        #    background-color: rgb(20, 20, 20);
        #    }
        # """)
        # MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_result_path_edit.setText(_translate("MainWindow", "НАС"))
        self.label.setText(_translate("MainWindow",
                                      "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\""
                                      " \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                      "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                      "p, li { white-space: pre-wrap; }\n"
                                      "</style></head><body style=\" font-family:\'MS Shell Dlg 2\';"
                                      " font-size:8pt; font-weight:400; font-style:normal;\">\n"
                                      "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; "
                                      "margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Період сек.</p>\n"
                                      "<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px;"
                                      "margin-left:0px; margin-right:0px; -qt-block-indent:0;"
                                      " text-indent:0px;\"><br /></p></body></html>"))

        self.pushButton_start.setText(_translate("MainWindow", "Старт"))
        self.pushButton_stop.setText(_translate("MainWindow", "Стоп"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.time_add.setText("OK")
        self.label_2.setText(' Об`єкти в сховищі')
